### 처음 실행하는 jupyternotebook


In [2]:
import numpy
data1 = [0,1,2,3,4,5]
a1 = numpy.array(data1)
a1

array([0, 1, 2, 3, 4, 5])

In [3]:
a1.dtype

dtype('int32')

In [4]:
numpy.array([0.5, 2, 0.01, 8])

array([0.5 , 2.  , 0.01, 8.  ])

In [8]:
numpy.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [2]:
import numpy
data10 = numpy.linspace(1,10,10)
data10

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [4]:
import xmltodict

xml_data = """
<?xml version="1.0" encoding="UTF-8" ?>
    <사용자정보>
        <이름>홍길동</이름>
        <나이>25</나이>
        <거주지>서울</거주지>
        <신체정보>
            <키 unit="cm">175.4</키>
            <몸무게 unit="kg">71.2</몸무게>
        </신체정보>
        <취미>등산</취미>
        <취미>자전거타기</취미>
        <취미>독서</취미>
    </사용자정보>
"""




ModuleNotFoundError: No module named 'xmltodict'

In [11]:
import xmltodict
xml_data = """
<?xml version="1.0" encoding="UTF-8" ?>
    <사용자정보>
        <이름>홍길동</이름>
        <나이>25</나이>
        <거주지>서울</거주지>
        <신체정보>
            <키 unit="cm">175.4</키>
            <몸무게 unit="kg">71.2</몸무게>
        </신체정보>
        <취미>등산</취미>
        <취미>자전거타기</취미>
        <취미>독서</취미>
    </사용자정보>
"""
print(xml_data)
dict_data = xmltodict.parse(xml_data, xml_attribs=True)
print(dict_data)


<?xml version="1.0" encoding="UTF-8" ?>
    <사용자정보>
        <이름>홍길동</이름>
        <나이>25</나이>
        <거주지>서울</거주지>
        <신체정보>
            <키 unit="cm">175.4</키>
            <몸무게 unit="kg">71.2</몸무게>
        </신체정보>
        <취미>등산</취미>
        <취미>자전거타기</취미>
        <취미>독서</취미>
    </사용자정보>



ExpatError: XML or text declaration not at start of entity: line 2, column 0